export const search = <i className="fa-solid fa-magnifying-glass"></i>
export const light = <i className="fa-solid fa-sun"></i>
export const dark = <i className="fa-solid fa-moon"></i>
export const chat = <i className="fa-solid fa-message"></i>
export const notification = <i className="fa-solid fa-bell"></i>
export const question = <i className="fa-solid fa-question"></i>
export const downarrow = <i className="fa-solid fa-caret-down"></i>
export const squaredropdown = <i className="fa-solid fa-square-caret-down"></i>
export const world = <i className="fa-solid fa-globe"></i>
export const edit = <i className="fa-solid fa-pen-to-square"></i>
export const locationIcon = <i className="fa-solid fa-location-dot"></i>
export const occupationIcon = <i className="fa-solid fa-briefcase"></i>
export const setting = <i className="fa-solid fa-gear"></i>
export const pen = <i className="fa-solid fa-pen"></i>
export const twitter = <i className="fa-brands fa-twitter"></i>
export const linkedin = <i className="fa-brands fa-linkedin"></i>
export const imageIcon = <i className="fa-solid fa-image"></i>
export const clipIcon = <i className="fa-regular fa-clipboard"></i>
export const attatchment = <i className="fa-solid fa-paperclip"></i>
export const audio = <i className="fa-solid fa-microphone"></i>
export const adduser = <i className="fa-solid fa-user-plus"></i>
export const removeuser = <i className="fa-solid fa-user-minus"></i>
export const like = <i className="fa-regular fa-heart"></i>
export const liked = <i className="fa-solid fa-heart"></i>
export const comment = <i className="fa-regular fa-comment"></i>
export const insta = <i className="fa-brands fa-instagram"></i>
export const facebook = <i className="fa-brands fa-square-facebook"></i>
export const deleteIcon = <i className="fa-solid fa-trash"></i>
export const threeDot = <i className="fa-solid fa-ellipsis"></i>
export const share = <i className="fa-solid fa-share-nodes"></i>
export const dublecheck = <i className="fa-solid fa-check-double"></i>